version: '3.8'
services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "5672:5672"
    volumes:
      - ./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    depends_on:
      - sqledge